export const LANGUAGES = {
  "en": "english",
  "zh_CN": "simplified chinese",
  "zh_TW": "traditional chinese",
  "ja": "japanese",
  "ko": "korean",
  "fr": "french",
  "es": "spanish",
  "ru": "russian",
  "ar": "arabic",
  "th": "thai",
  "de": "german",
  "pt": "portuguese",
  "it": "italian",
  "hi": "hindi",
  "id": "indonesian",

  "tr": "turkish",
  "vi": "vietnamese",
  "he": "hebrew",
  "el": "greek",
  "pl": "polish",
  "nl": "dutch",
  "hu": "hungarian",
  "no": "norwegian",
  "sv": "swedish",
  "fi": "finnish",
  "cs": "czech",
  "da": "danish",
  "lt": "lithuanian",
  "sk": "slovak",
  "ms": "malay",
  "ro": "romanian",
  "bg": "bulgarian",
  "hr": "croatian",
  "lo": "lao",
  "ur": "urdu",
  "ta": "tamil",

  // "uk": "ukrainian",
  // "ca": "catalan",
  // "la": "latin",
  // "mi": "maori",
  // "ml": "malayalam",
  // "cy": "welsh",
  // "te": "telugu",
  // "fa": "persian",
  // "lv": "latvian",
  // "bn": "bengali",
  // "sr": "serbian",
  // "az": "azerbaijani",
  // "sl": "slovenian",
  // "kn": "kannada",
  // "et": "estonian",
  // "mk": "macedonian",
  // "br": "breton",
  // "eu": "basque",
  // "is": "icelandic",
  // "hy": "armenian",
  // "ne": "nepali",
  // "mn": "mongolian",
  // "bs": "bosnian",
  // "kk": "kazakh",
  // "sq": "albanian",
  // "sw": "swahili",
  // "gl": "galician",
  // "mr": "marathi",
  // "pa": "punjabi",
  // "si": "sinhala",
  // "km": "khmer",
  // "sn": "shona",
  // "yo": "yoruba",
  // "so": "somali",
  // "af": "afrikaans",
  // "oc": "occitan",
  // "ka": "georgian",
  // "be": "belarusian",
  // "tg": "tajik",
  // "sd": "sindhi",
  // "gu": "gujarati",
  // "am": "amharic",
  // "yi": "yiddish",
  // "uz": "uzbek",
  // "fo": "faroese",
  // "ht": "haitian creole",
  // "ps": "pashto",
  // "tk": "turkmen",
  // "nn": "nynorsk",
  // "mt": "maltese",
  // "sa": "sanskrit",
  // "lb": "luxembourgish",
  // "my": "myanmar",
  // "bo": "tibetan",
  // "tl": "tagalog",
  // "mg": "malagasy",
  // "as": "assamese",
  // "tt": "tatar",
  // "haw": "hawaiian",
  // "ln": "lingala",
  // "ha": "hausa",
  // "ba": "bashkir",
  // "jw": "javanese",
  // "su": "sundanese",
} as const;
