import { LANGS } from "../../electron/sql";

export const availableLangs: { id: keyof LANGS, name: string}[] = [
  { id: 'en', name: '英语' },
  { id: 'zh_CN', name: '简体中文' },
  { id: 'zh_TW', name: '繁体中文' },
  { id: 'ja', name: '日语' },
  { id: 'ko', name: '韩语' },
  { id: 'fr', name: '法语' },
  { id: 'es', name: '西班牙语' },
  { id: 'ru', name: '俄语' },
  { id: 'ar', name: '阿拉伯语' },
  { id: 'th', name: '泰语' },
  { id: 'de', name: '德语' },
  { id: 'pt', name: '葡萄牙语' },
  { id: 'it', name: '意大利语' },
  { id: 'hi', name: '印地语' },
  { id: 'id', name: '印尼语' },

  { id: 'tr', name: '土耳其语' },
  { id: 'vi', name: '越南语' },
  { id: 'he', name: '希伯来语' },
  { id: 'el', name: '希腊语' },
  { id: 'pl', name: '波兰语' },
  { id: 'nl', name: '荷兰语' },
  { id: 'hu', name: '匈牙利语' },
  { id: 'no', name: '挪威语' },
  { id: 'sv', name: '瑞典语' },
  { id: 'fi', name: '芬兰语' },
  { id: 'cs', name: '捷克语' },
  { id: 'da', name: '丹麦语' },
  { id: 'lt', name: '立陶宛语' },
  { id: 'sk', name: '斯洛伐克语' },
  { id: 'ms', name: '马来语' },
  { id: 'ro', name: '罗马尼亚语' },
  { id: 'bg', name: '保加利亚语' },
  { id: 'hr', name: '克罗地亚语' },
  { id: 'lo', name: '老挝语' },
  { id: 'ur', name: '乌尔都语' },
  { id: 'ta', name: '泰米尔语' },
];
